### ISSUE TITLE
VS2017 support

### ISSUE THREAD

**Issue by grokky1** [Serg046/MsBuildTaskExplorer#14]
VS2017 support would be great!

**Comment by Serg046** [comment]
Done.
Use [MsBuild Task Explorer 1.2](https://visualstudiogallery.msdn.microsoft.com/44f2ec71-6ef2-4149-b570-fdf337b37fc4).

**Comment by grokky1** [comment]
@Serg046 I can't understand why, but it crashes my VS2017. Maybe it's a plugin conflict, I can't narrow down the cause.

I assume it works for you.

**Comment by Serg046** [comment]
Yes, I just install add-in, create a simple console solution and build by MsBuild Task Explorer. It works fine for me.

Please provide more details about the issue. When exactly does it happen, error/exception info etc.

**Comment by grokky1** [comment]
@Serg046 

I open it via Edit > Other Windows > then choose it from the list.

Either it shows a small floating blank window, or it just crashes VS without showing an error (just asks me to terminate it). When I restart VS, it isn't enabled, but I can choose it again, and it crashes again, etc.

My environment:
VS2017 latest build - 15.2 26430.6
Win10 x64
Solution contains ASP.NET Core projects and .NET Core projects

**Comment by Serg046** [comment]
If you have Backup folder in the solution try to delete and use as workaround.
I will fix it and add Info Window to print an exception and not crash VS.
Thank you for your catch!

**Comment by grokky1** [comment]
Unfortunately new version still crashes for me
Maybe there is a log file somewhere that has the errors?

Otherwise we need to wait to see if anyone else has a similar problem

BTW this is what happens:

Scenario 1. I open VS, open solution, then open the tool, it crashes.

Scenario 2. I close solution. Open tool. It is blank but doesn't crash. Close VS. Open VS, open solution, it doesn't crash, but tool window is still empty.

**Comment by Serg046** [comment]
> Unfortunately new version still crashes for me

1.2.1?

> Maybe there is a log file somewhere that has the errors?

 Try to find: "C:\Users\ ... \Microsoft\VisualStudio\15.0\ActivityLog.xml":

P.S. Try to use with simple classic console application. It needs to understand root cause...

**Comment by Serg046** [comment]
Also you can find an error in the Windows Event Viewer. I've just tried to install back `v1.2`, open .net core sln with Backup folder and see that Event Viewer shows error info.

But please be sure you use `1.2.1`. I am able to reproduce your two scenarios only in `1.2`.

**Comment by grokky1** [comment]
Yeah I was using 1.2.1. The log didn't help, but I found something interesting in the event viewer!

````
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.PathTooLongException
   at System.IO.Path.LegacyNormalizePath(System.String, Boolean, Int32, Boolean)
   at System.IO.Path.NormalizePath(System.String, Boolean, Int32, Boolean)
   at System.IO.Path.InternalGetDirectoryName(System.String)
   at System.IO.FileSystemEnumerableIterator`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]..ctor(System.String, System.String, System.String, System.IO.SearchOption, System.IO.SearchResultHandler`1<System.__Canon>, Boolean)
   at System.IO.DirectoryInfo.InternalGetFiles(System.String, System.IO.SearchOption)
   at System.IO.DirectoryInfo.GetFiles(System.String)
   at System.Linq.Enumerable.Aggregate[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Collections.Generic.IEnumerable`1<System.__Canon>, System.__Canon, System.Func`3<System.__Canon,System.__Canon,System.__Canon>)
   ...etc...
   at MsBuildTaskExplorer.SolutionInfo.GetMsBuildTasks(System.IO.DirectoryInfo)
   at MsBuildTaskExplorer.SolutionInfo.GetMsBuildTasks()
   at MsBuildTaskExplorer.TaskExplorerWindowControl.UpdateTaskList()
   at MsBuildTaskExplorer.TaskExplorerWindowControl.OnLoaded(System.Object, System.Windows.RoutedEventArgs)
````

**The problem is `System.IO.PathTooLongException` !!**

In ASP.NET Core projects, there is the `node_modules` and `bower_components` directories, and they are HUNDREDS of directories deep. The extension scans into those directories and fails (I forgot to tell you that it takes about 10-15 seconds before it crashes).

[The problem is probably somehere here](https://github.com/Serg046/MsBuildTaskExplorer/commit/d582f3f42809dc47f9dbdb0cccb3badbf30e450a#diff-cf7309a78b052f381c7e9f7f848f22a7L81). Maybe it should only scan two directories below the solution file. Or five, something like that.

A typical structure:

- MySolution\
  - MySolution.sln
  - src\
    - Foo\
      - Foo.csproj
    - Bar\
      -  Bar.csproj
      - node_modules\
      - bower_components\
  - test\
    - FooTests\
      - FooTests.csproj
    - BarTests\
      - BarTests.csproj

**Comment by Serg046** [comment]
3432fb1

**Comment by Serg046** [comment]
#15
